[package]
name = "rust_cards"
version = "0.1.0"
edition = "2021"
authors = ["Ardu"]

[lib]
name = "rust_cards"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "0.7.0"